#INCLUDE "TOTVS.CH"
#INCLUDE "TOTVS.CH"
#INCLUDE "PARMTYPE.CH"

/*
ARRAYS SAO COLEÇÕES DE VALORES SEMELHANTES A UMA LISTA.
CADA ITEM EM UM ARRAY E REFERENCIADO PELA INDICAÇÃO DE SUA POSIÇÃO NUMERICA
INICIANDO PELO NUMERO 1.
*/

User Function CNAR001()
Local dData := Date()
Local aValores := {"João", dData, 100}

Alert(aValores[2]) //EXIBE A POSIÇÂO 2 DO ARRAY - dData
Alert(aValores[3]) //EXIBE A POSIÇÂO 3 DO ARRAY - 100
Alert(aValores[1]) //EXIBE A POSIÇÂO 1 DO ARRAY - João

Return
