#INCLUDE "rwmake.ch"
#INCLUDE "TOPCONN.CH"

/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณGENA004      บ Autor ณ Vinicius Lan็a  บ Data ณ  29/02/2012 บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDescricao ณ Acerta E2_ARQRAT                                           บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ GEN                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
/*/
                       
User Function GENA004()


Processa({|| U_GENA004A() },"Processando...")     


Return
 
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณGENA004A  บAutor  ณVinicius Lan็a      บ Data ณ  03/21/12   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ Acerta E2_ARQRAT                                           บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ GEN                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/

User Function GENA004A()


//ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ
//ณ Declaracao de Variaveis                                             ณ
//ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู
Local cQuery
Local cArqtmp	:= GetNextAlias()  
Local ctitulo_	:= ""


cQuery := " SELECT SE2.E2_FILIAL, SE2.E2_PREFIXO, SE2.E2_NUM, SE2.E2_PARCELA, SE2.E2_FORNECE, SE2.E2_LOJA, SE2.E2_NOMFOR, SE2.E2_VALOR, "
cQuery += " SE2.E2_CONTAD, SE2.E2_ARQRAT, SE2.E2_EMISSAO, CV4.CV4_FILIAL, CV4.CV4_DTSEQ, CV4.CV4_SEQUEN, CV4.CV4_DEBITO, CV4.CV4_PERCEN, "
cQuery += " CV4.CV4_VALOR, CV4.CV4_CCD, CV4.CV4_ITEMD, CV4.CV4_CLVLDB "
cQuery += " FROM SE2000 SE2, CV4000 CV4                               "
cQuery += " WHERE SE2.D_E_L_E_T_=' ' AND CV4.D_E_L_E_T_= ' '          "
cQuery += " AND SE2.E2_RATEIO='S'                                     "
cQuery += " AND SE2.E2_ARQRAT <> ' '                                  "
cQuery += " AND CV4.CV4_FILIAL = SE2.E2_FILIAL                        "
cQuery += " AND CV4.CV4_DTSEQ = SE2.E2_EMISSAO                        "
//cQuery += " AND SUBSTR(CV4.CV4_SEQUEN,1,8) = SUBSTR(SE2.E2_ARQRAT,13,8) "
cQuery += " AND SUBSTR(CV4.CV4_SEQUEN,1,10) <> SUBSTR(SE2.E2_ARQRAT,13,10)  "
cQuery += " ORDER BY SE2.E2_FILIAL, SE2.E2_PREFIXO, SE2.E2_NUM, SE2.E2_PARCELA, SE2.E2_TIPO, SE2.E2_FORNECE, SE2.E2_LOJA, CV4.CV4_ITSEQ "

If Select(cArqtmp) > 0
	dbSelectArea(cArqtmp)
	dbCloseArea()
EndIf

DbUseArea(.T., 'TOPCONN', TCGenQry(,,cQuery), cArqtmp, .F., .T.)

DbSelectArea(cArqtmp)
DbGoTop()

Do While !(cArqtmp)->(Eof()) 

//If ((cArqtmp)->E2_FILIAL+(cArqtmp)->E2_PREFIXO+(cArqtmp)->E2_NUM+(cArqtmp)->E2_PARCELA+(cArqtmp)->E2_FORNECE) <> ctitulo_

//	ctitulo_ := (cArqtmp)->E2_FILIAL+(cArqtmp)->E2_PREFIXO+(cArqtmp)->E2_NUM+(cArqtmp)->E2_PARCELA+(cArqtmp)->E2_FORNECE
	
 	cQuery:= " UPDATE SE2000 SET E2_ARQRAT = '" + (cArqtmp)->CV4_FILIAL+(cArqtmp)->CV4_DTSEQ+(cArqtmp)->CV4_SEQUEN+ "'"
	cQuery+= " WHERE E2_FILIAL = '"+ (cArqtmp)->E2_FILIAL + "'"
	cQuery+= " AND E2_PREFIXO = '" + (cArqtmp)->E2_PREFIXO + "'"
	cQuery+= " AND E2_NUM = '" + (cArqtmp)->E2_NUM + "'"
	cQuery+= " AND E2_PARCELA = '" + (cArqtmp)->E2_PARCELA + "'"
	cQuery+= " AND E2_FORNECE = '" + (cArqtmp)->E2_FORNECE + "'"
	cQuery+= " AND E2_LOJA = '" + (cArqtmp)->E2_LOJA + "'" 
	cQuery+= " AND D_E_L_E_T_ = ' ' "
	
	TCSQLEXEC(cQuery)
	
//EndIf

(cArqtmp)->(DbSkip())

Enddo       

alert("processo finalizado...")

Return